<a href="https://colab.research.google.com/github/RonakMehta21/DeepLearningWithPyTorch/blob/master/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2 Code inspired from [Deep Learning with PyTorch](https://pytorch.org/assets/deep-learning/Deep-Learning-with-PyTorch.pdf)

In [0]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [0]:
a[2] = 3.0

In [4]:
a

[1.0, 2.0, 3.0]

In [0]:
import torch

In [0]:
a = torch.ones(3)

In [7]:
a

tensor([1., 1., 1.])

In [9]:
a[1]

tensor(1.)

In [11]:
float(a[1])

1.0

In [0]:
a[2] = 2.0

In [13]:
a

tensor([1., 1., 2.])

In [0]:
points = torch.zeros(6)

In [0]:
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

In [0]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])

In [17]:
points

tensor([1., 4., 2., 1., 3., 5.])

In [18]:
float(points[0]), float(points[1])

(1.0, 4.0)

In [19]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [20]:
points.shape

torch.Size([3, 2])

In [22]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [24]:
points[0, 1]

tensor(4.)

In [25]:
points[0]

tensor([1., 4.])

In [26]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [27]:
points_storage = points.storage()
points_storage[0]

1.0

In [28]:
points.storage()[1]

4.0

In [29]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [30]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()

2

In [31]:
second_point.size()

torch.Size([2])

In [32]:
second_point.shape

torch.Size([2])

In [33]:
points.stride()

(2, 1)

In [34]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [35]:
second_point.storage_offset()

2

In [36]:
second_point.stride()

(1,)

In [37]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [38]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [39]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [40]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [41]:
id(points.storage()) == id(points_t.storage())

True

In [42]:
points.stride()

(2, 1)

In [43]:
points_t.stride()

(1, 2)

In [44]:
some_tensor = torch.ones(3, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor.shape

torch.Size([3, 4, 5])

In [45]:
some_tensor_t.shape

torch.Size([5, 4, 3])

In [46]:
some_tensor.stride()

(20, 5, 1)

In [47]:
some_tensor_t.stride()

(1, 5, 20)

In [48]:
points.is_contiguous()

True

In [49]:
points_t.is_contiguous()

False

In [50]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [51]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [52]:
points_t.stride()

(1, 2)

In [53]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [54]:
points_t_cont.stride()

(3, 1)

In [55]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [57]:
short_points.dtype

torch.int16

In [0]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [0]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [0]:
points = torch.randn(10, 2)
short_points = points.type(torch.short)

In [8]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [0]:
points = torch.from_numpy(points_np)

In [1]:
!conda install h5py

/bin/bash: conda: command not found


In [0]:
import h5py

In [0]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]],
device='cuda')

In [0]:
points_gpu = points.to(device='cuda')

In [0]:
points_gpu = points.to(device='cuda:0')

In [0]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda') 

In [0]:
points_gpu = points_gpu + 4

In [0]:
points_cpu = points_gpu.to(device='cpu')

In [0]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [0]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

In [0]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

In [0]:
a = torch.ones(3, 2)

In [22]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])